on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install node modules
        run: npm install

      - name: Build app
        run: npm run build  

      - name: Delete previous artifacts
        run: aws s3 rm s3://${{ secrets.BUCKET_NAME }} --recursive
      
      - name: Deploy
        run: cd public && aws s3 sync . s3://${{ secrets.BUCKET_NAME }}
